# Generated by Django 3.1.2 on 2020-11-07 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedpeople',
            name='gift_amount_pred',
            field=models.IntegerField(blank=True, null=True, verbose_name='礼金金额预计'),
        ),
        migrations.AddField(
            model_name='invitedpeople',
            name='gift_amount_real',
            field=models.IntegerField(blank=True, null=True, verbose_name='礼金金额实际'),
        ),
        migrations.AddField(
            model_name='invitedpeople',
            name='has_gift',
            field=models.BooleanField(null=True, verbose_name='收礼金'),
        ),
        migrations.AlterField(
            model_name='invitedpeople',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='归类'),
        ),
        migrations.AlterField(
            model_name='invitedpeople',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.table', verbose_name='桌子'),
        ),
    ]
