# Generated by Django 3.1.2 on 2020-11-07 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201107_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名称')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='日期时间')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('related_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.family', verbose_name='关联家庭')),
            ],
            options={
                'verbose_name': '宴席',
                'verbose_name_plural': '宴席',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invitedpeople',
            name='session',
            field=models.ManyToManyField(to='main.Session', verbose_name='受邀宴席'),
        ),
        migrations.AddField(
            model_name='table',
            name='related_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.session', verbose_name='宴席'),
        ),
    ]
